### ISSUE TITLE
Going in a world in single player  gets stuck at 100% loading.

### ISSUE THREAD

**Issue by rakostep** [spoorn/sodium-forge#89]
### Expected Behavior
Can open the world normally and won't take an hour or above to load.

### Actual Behavior
Seems like it's stuck at 100% with undetermined time (I left it for 4 hours and still stuck)

### Reproduction Steps
Not sure if reproduceable since it might be my laptop specs, but here's a list of the mods with it:

### Attachments
none

### [Optional] Server/Client logs
N/A

### Mods list
```
betterwithminecolonies-1.16.4-1.16.17
createchunkloading-0.2.0
chiselsandbits-0.3.4-RELEASE
paperbooks_1.16.5-1.3
bamboospreads_1.16.5-2.0
ChickenDropFeathers-1.0-forge-1.16.5-36.0.0
collective-1.16.5-2.27
corpse-1.16.5-1.0.5
Guns'n'Glory-2.1
Chunk Pregenerator-V1.16-3.0.5
WoolToString-1.16.x-1.0.1
smoothboot-forge-1.16.4-1.2.2
immersiveweapons-1.16.5-1.1.1
MouseTweaks-2.14-mc1.16.2
archers_paradox-1.16.4-1.2.0
cofh_core-1.16.4-1.2.1
pptowers-1.0.3
spiders-2.0-1.16.4-1.0.4
comforts-forge-1.16.5-4.0.1.1
hole_filler_mod-1.2.4.2-mc_1.16.x-forge
filler-1.0.0
mining_helmet-1.16.5-2.0.1
backpacked-1.10.1-1.16.3
TerraForged-1.16.5-0.2.12
bambootweaks-2.0.5-forge
bamboo2-1.16.5_0.3.1
scaffoldingpower-1.16.5-1.3.0
factoriores-1.1
searchlight-1.16-forge-1.1.1
[Forge-1.16.5] Hololive Relics (2.0.0)
DiagonalFences-v1.1.1-1.16.5
PuzzlesLib-v1.0.7-1.16.5
creategears-1.16.5-1.1.0
morecreatestuffs-mc1.16-b1.4.0
createplus-1.16.4_v0.3.2
guardscraft-1.16.5-1.1.0Beta
FpsReducer-mc1.16.5-1.20
jmt_mcmt-1.16.5-0.21.80
adaptive_performance_tweaks_1.16.5-1.1.1
jmt_mcmt-1.16.5-0.21.80-modcore
RepairChests-1.16.5-1.7
EpicFightMod-1.16.5-4.1.5
SakuraBiome_v1.2(1.16.5)
create-addon-v4
kotlinforforge-1.14.0-obf
flywheel-1.16-0.1.1
Mantle-1.16.5-1.6.115
TConstruct-1.16.5-3.1.0.231
minecolonies-0.14.290-ALPHA-universal
StimpakMod-1.16.5-0.3.2
scarecrowsterritory-1.1.0-mc1.16.5
supermartijn642configlib-1.0.8-mc1.16
supermartijn642corelib-1.0.10-mc1.16.5
ChickenChunks-1.16.5-2.8.0.86-universal
CodeChickenLib-1.16.5-4.0.2.427-universal
chunksavingfix-0.1.0
MiniEffects-1.16.5-0.0.2
Xaeros_Minimap_21.13.0_Forge_1.16.5
stackrefill_1.16.5-1.8
nohostilesaroundcampfire_1.16.5-3.4
LongerDays-2.0.0-mc1.16.4
art_artillery1.16.5-1.0.7
StupidWeapons v1.7 - 1.16.5 forge
createaddition-1.16.5-20210626a
create-mc1.16.5_v0.3.1c
dungeons_gear-1.16.5-3.0.17
simplewoodenpipes-1.16.5-2.0
woodenhopper-1.1.0-1.16.2+
woodarmor-1.16.5
Postlamp_mc1.16.5_v1.2.0
PlayTics Deco 1.16 v.0.1.3
structurize-0.13.200-BETA-universal
tetrapak-0.2.3
SereneSeasons-1.16.5-4.0.1.120-universal
architectury-1.20.28-forge
ferritecore-2.0.5-forge
RingOfRepair-Forge-1.16.5-1.2.15
mcw-doors-1.0.3-mc1.16.5
CraftTweaker-1.16.5-7.1.0.346
create-stuff-additions1.16.5_v1.0.6
CreateTweaker-1.0.0.14
JEITweaker-1.16.5-1.0.1.33
branders-sulfurpotassiummod-2.3.1-1.16.5
jei-1.16.5-7.7.1.110
JRFTL [1.16.5]-1.2
SpearWeapons_1.16.5
tetra-1.16.5-3.14.1
tetranomicon-1.3
mgui-1.16.5-3.2.0
ThrowableExplosives-1.16.5-1.1.0
```

### System Information

- Java Version: 1.8.0_271
- CPU: Intel(R) Pentium(R) CPU 4415Y @ 1.60GHz
- GPU: Intel(R) HD Graphics 615
- Sodium Reforged Version: latest

**Comment by Darkmega18** [comment]
aha! I had a feeling it was here. I had such a bug with latest forge 36.1.61 and probably later. I'm currently sitting at 36.1.24. a brief look at changelog and putting 2 and 2 together for the update to ars nouveau that forced me to update to it briefly and experience the bug, I think they made some kind of lighting changes or experimental stuff which is probably not liking it. no console reports or anything. it just... sticks. and if something sticks longer than a minute or so, I know something is up, cause otherwise it should go in within a few seconds.

Although I salute rakostep's persistence to leave it for 4 hours. :V

**Comment by Darkmega18** [comment]
ok, I have confirmed for myself that turning off sodium from the mod list allowed my worlds to load. in forge 36.1.62. please take a look at what forge is doing and fix this when you can. 

A friend of mine has... issues with animated textures and stuff when her PC plays modpacks and such and lags profusely without sodium or optifine being available to shut them off. So for their sake atleast, I need this installed eventually when I go to test with them and others. also, the optimizations provided is always a plus provided my game doesn't crash in general from it.

if it's not directly related to you, this is a modlist that I'm using currently:
https://cdn.discordapp.com/attachments/747181991010500690/866302803626819594/unknown.png

**Comment by Darkmega18** [comment]
as far as I can tell, this somehow either fixed itself or got fixed with the last update that was posted.

**Comment by spoorn** [comment]
please reopen if the issue persists

**Comment by rakostep** [comment]
Hi again, thanks for the inputs you guys, though apparently  I still encounter the issue even though I have updated the mod. Sorry for the bother.

**Comment by spoorn** [comment]
You can try to see if you can narrow it down to some mod conflict by removing half your mods at a time to pinpoint which mod causes the freeze along with Sodium

**Comment by jakeb072001** [comment]
lithium and mcmt don't work together. add these to your config and it should work:
mixin.world.chunk_access=false
mixin.world.tick_scheduler=false
mixin.alloc.chunk_ticking=false
mixin.world.block_entity_ticking=false
mixin.alloc.chunk_random=false

if it still doesn't work then there is something else in addition to this causing the issue.
I'm not sure which gives better performance though, mcmt with these settings or no mcmt without these settings.
